version: "2"

services:
  mail_client:
    build:
      context: ./mail_fe
    ports:
      - "8000:3000"
    volumes:
      - ./mail_fe:/usr/src/app

  mail_service:
    build:
      context: ./mail_be
    ports:
      - "8080:8000"
    volumes:
      - ./mail_be:/mailservice
