version: "2"

services:
  mailclient:
    build:
      context: ./mail_fe
    ports:
      - "8000:3000"
    volumes:
      - .:/usr/src/app

  mailservice:
    build:
      context: ./mail_be
    ports:
      - "8080:8000"
    volumes:
      - .:/mailservice
