# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-30 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_mail', models.EmailField(max_length=200)),
                ('from_mail', models.EmailField(max_length=200)),
                ('subject', models.CharField(blank=True, default='', max_length=200)),
                ('text', models.CharField(blank=True, default='', max_length=5000)),
                ('status', models.CharField(choices=[('S', 'Success'), ('F', 'Fail')], default='F', max_length=1)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
