# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-27 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailservice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='from_mail',
            field=models.EmailField(max_length=200),
        ),
        migrations.AlterField(
            model_name='mail',
            name='to_mail',
            field=models.EmailField(max_length=200),
        ),
    ]
