# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-29 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailservice', '0002_auto_20180527_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='status',
            field=models.CharField(choices=[('S', 'Success'), ('F', 'Fail')], default='F', max_length=1),
        ),
    ]
